const getConstants = () => {
        return {
          ahfc_honda_black : "ahfc-honda-black",
          ahfc_honda_blue : "ahfc-honda-blue",
          ahfc_honda_red : "ahfc-honda-red",
          ahfc_honda_navyBlue : "ahfc-honda-navyblue",
          BLANK : "",
          SUCCESS: "Success",
          ACCOUNT_TYPE_RETAIL : "Retail",
          ACCOUNT_TYPE_BALOON : "Balloon",
          ACCOUNT_NOT_FOUND: "Account Not Found",
          ALREADY_REGISTERED: "Already Registered",
          EXCEPTION: "Exception has occurred",
          INVALID_DATE: "Invalid Date",
          ENROLL_EASYPAY: "Enroll in EasyPay",
          EASYPAY: "EASYPAY",
          ONE_TIME: "One-Time",
          ONE_TIME_PAYMENT: "ONE-TIME PAYMENT",
          PAYOFF_LC: "Payoff",
          PAYOFF_UC: "PAYOFF",
          RECURRING: "Recurring",
          PENDING: "Pending",
          PROCESSING: "Processing",
          SUSPENDED: "Suspended",
          CANCELLED: "Cancelled",
          COMPLETED: "Complete",
          STOPPED: "Stopped",
          RESEARCHING: "Researching",
          SCHEDULED: "Scheduled",
          LEASE: "Lease",
          OTP_PRINCIPAL: "OTP Principal",
          OTP_STANDARD: "OTP Standard",
          STANDARD: "Standard",
          PRINCIPAL: "Principal",
          STANDARD_PAYMENT_AMOUNT: "Standard Payment Amount",
          PRINCIPAL_PAYMENT_AMOUNT: "Principal Payment Amount",
          PAYOFF_AMOUNT: "Payoff Amount",
          UNDEFINED: "undefined",
          CHECKING: "Checking",
          FAILED: "FAILED",
          NRC: "NRC",
          ST: "st",
          ND: "nd",
          RD: "rd",
          TH: "th",
          ENABLED: "enabled",
          DISABLED: "disabled",
          MONTHLYAMT: "MONTHLY PAYMENT AMOUNT",
          ADDPAYAMT: "ADDITIONAL PAYMENT AMOUNT",
          ADDERRORMSG:
            "An internal exception happened during current operation. Please contact system administrator with this exception details:",
          ADDACCERRORMSG: "Please enter all the required fields.",
          JAN: "JAN",
          FEB: "FEB",
          MAR: "MAR",
          APR: "APR",
          MAY: "MAY",
          JUN: "JUN",
          JUL: "JUL",
          AUG: "AUG",
          SEP: "SEP",
          OCT: "OCT",
          NOV: "NOV",
          DEC: "DEC",
          MONTHS: [
            "JAN",
            "FEB",
            "MAR",
            "APR",
            "MAY",
            "JUN",
            "JUL",
            "AUG",
            "SEP",
            "OCT",
            "NOV",
            "DEC"
          ],
          MONTHS_LC: [
            "Jan",
            "Feb",
            "Mar",
            "Apr",
            "May",
            "Jun",
            "Jul",
            "Aug",
            "Sep",
            "Oct",
            "Nov",
            "Dec"
          ],
          FROMDATE: "fromdate",
          TODATE: "todate",
          dateasc: "dateasc",
          datedesc: "datedesc",
          totalasc: "totalasc",
          totaldesc: "totaldesc",
          mdate: "date",
          asc: "asc",
          total: "total",
          desc: "desc",
          sortcombo: "sortcombo",
          fromdatemob: "fromdatemob",
          todatemob: "todatemob",
          MONTHSTEXT: {
            JAN: "JANUARY",
            FEB: "FEBRUARY",
            MAR: "MARCH",
            APR: "APRIL",
            MAY: "MAY",
            JUN: "JUNE",
            JUL: "JULY",
            AUG: "AUGUST",
            SEP: "SEPTEMBER",
            OCT: "OCTOBER",
            NOV: "NOVEMBER",
            DEC: "DECEMBER"
          },
          listData: [
            { label: "1st of the month", value: 1 },
            { label: "2nd of the month", value: 2 },
            { label: "3rd of the month", value: 3 },
            { label: "4th of the month", value: 4 },
            { label: "5th of the month", value: 5 },
            { label: "6th of the month", value: 6 },
            { label: "7th of the month", value: 7 },
            { label: "8th of the month", value: 8 },
            { label: "9th of the month", value: 9 },
            { label: "10th of the month", value: 10 },
            { label: "11th of the month", value: 11 },
            { label: "12th of the month", value: 12 },
            { label: "13th of the month", value: 13 },
            { label: "14th of the month", value: 14 },
            { label: "15th of the month", value: 15 },
            { label: "16th of the month", value: 16 },
            { label: "17th of the month", value: 17 },
            { label: "18th of the month", value: 18 },
            { label: "19th of the month", value: 19 },
            { label: "20th of the month", value: 20 },
            { label: "21th of the month", value: 21 },
            { label: "22th of the month", value: 22 },
            { label: "23th of the month", value: 23 },
            { label: "24th of the month", value: 24 },
            { label: "25th of the month", value: 25 },
            { label: "26th of the month", value: 26 },
            { label: "27th of the month", value: 27 },
            { label: "28th of the month", value: 28 },
            { label: "29th of the month", value: 29 },
            { label: "30th of the month", value: 30 },
            { label: "31th of the month", value: 31 }
          ]
        };
      };
      export { getConstants };